//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTrackerProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class SystemUser
    {
        public int UserId { get; set; }
        [DisplayName("User Name")]
        [Required(ErrorMessage = "Please enter a username.")]
        public string UserName { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Please enter a password.")]
        public string Password { get; set; }
        [DataType(DataType.Password)]
        [DisplayName("Re-enter Password")]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }
        [DisplayName("Email ID")]
        [Required(ErrorMessage = "Please enter an e-mail address.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please tick if you are an admin.")]

        public bool AdminRole { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
