//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTrackerProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.ExpenseAmount = 0m;
        }
    
        public int TransactionId { get; set; }
        public decimal ExpenseAmount { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public Nullable<int> FKDeptId { get; set; }
        public Nullable<int> FKEmpId { get; set; }
        public int FKTransModeId { get; set; }
        public string TransactionDescription { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual TransactionMode TransactionMode { get; set; }
    }
}
